version: "3.8"

services:
  db:
    image: postgres:15
    container_name: feedback_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: feedback
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: feedback_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/feedback
    ports:
      - "5000:5000"
    command: >
      sh -c "npx prisma migrate deploy &&
             npx prisma db seed &&
             npm run start"

volumes:
  pgdata:
