version: '3.8'
services:
  # 1️⃣ PostgreSQL БД
  db:
    image: postgres:15
    restart: always
    container_name: feedback_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2️⃣ Бэкенд-сервер
  app:
    build: .
    restart: always
    container_name: feedback_app
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@db:5432/mydatabase"
      PORT: 5000
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
